modLoader="javafml"
loaderVersion="[1,)"
license="OSL-3.0"
issueTrackerURL="${issue_url}"

[[mixins]]
config="nolijium.mixins.json"

[[mods]]
modId="nolijium"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="icon.png"
authors="${nolij}"
description="""
${mod_description}
"""

[[dependencies.nolijium]]
modId="neoforge"
type="required"
versionRange="${mod_loader_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.nolijium]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.nolijium]]
modId="embeddium"
type="optional"
versionRange="${embeddium_range}"
ordering="AFTER"
side="CLIENT"
